# Generated by Django 4.1.7 on 2023-03-11 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_rename_fechadeentraga_entregable_fecha_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entregable',
            old_name='fecha',
            new_name='fechaEntrega',
        ),
    ]
