# Generated by Django 4.1.7 on 2023-03-11 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_rename_fecha_entregable_fechaentrega'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entregable',
            old_name='fechaEntrega',
            new_name='fecha',
        ),
    ]
