# Generated by Django 4.1.7 on 2023-03-11 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_rename_fechaentrega_entregable_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entregable',
            old_name='fecha',
            new_name='fechaEntrega',
        ),
    ]
